### ISSUE TITLE
Install.sh unavailable due to billing issue

### ISSUE THREAD

**Issue by BeehiveSystems** [sharadregoti/devops-cli#18]
When running `curl https://storage.googleapis.com/devops-cli-artifacts/releases/devops/0.5.3/install.sh`, an error associated to billing appears. 

Workaround is to download the install.sh file from the repo, but the instructions should be updated.

https://github.com/sharadregoti/devops-cli/blob/master/install.sh

**Comment by sharadregoti** [comment]
Fixed!
